#docker-compose.yaml
#version: '2.231.0'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: darren
      POSTGRES_PASSWORD: letmein
    volumes:
      - db-data:/var/lib/postgressql/data
    networks:
      - webnet
volumes:
  db-data:
networks:
  webnet:
